//
//  Config.swift
//  Katana
//
//  Copyright © 2021 Bending Spoons.
//  Distributed under the MIT License.
//  See the LICENSE file for more information.

import ProjectDescription

let config = Config(
  generationOptions: [
    .disableAutogeneratedSchemes,
  ]
)
