project: Katana

documentation:
  author: Bending Spoons Team
  author_url: http://bendingspoons.com
  github_url: https://github.com/BendingSpoons/katana-swift

cocoapods:
  public_repo:
    email: opensource@bendingspoons.com
    author: Bending Spoons
  skip_linting: true

tests:
  runs:
    - scheme: Katana
      sdk: iphonesimulator12.1
      simulator: platform=iOS Simulator,OS=12.1,name=iPhone 8