included:
  - Katana
  - KatanaTests
  - Demo

whitelist_rules:
  - closing_brace
  - closure_spacing
  - colon
  - comma
  - control_statement
  - empty_count
  - explicit_init
  - file_length
  - function_body_length
  - implicit_getter
  - leading_whitespace
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_nsgeometry_functions
  - line_length
  - mark
  - opening_brace
  - operator_whitespace
  - overridden_super_call
  - private_unit_test
  -  redundant_nil_coalescing
  - return_arrow_whitespace
  - statement_position
  - switch_case_on_newline
  - syntactic_sugar
  - todo
  - trailing_comma
  - trailing_newline
  - trailing_semicolon
  - type_body_length
  - type_name
  - variable_name
  - vertical_whitespace

line_length: 130

file_length:
  warning: 600

function_body_length:
  warning: 100
  error: 200

variable_name:
  min_length: 1